name: Check Prettier

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: run prettier
        uses: simonlk1/prettier_action@v4.1.2
        with:
          prettier_plugins: prettier-plugin-svelte
          prettier_options: --check --plugin-search-dir=. src/**/*.{html,js,ts,svelte}
          